#ifndef ID_ITEMS_H
#define ID_ITEMS_H

#include <climits>
// Comilation fails without this
#include <map>

namespace item {
	// Order never changes!
	enum Id : uint16_t {
		NONE = 0,
		DIRT,
		STONE,
		BASIC_SWORD,
		BASIC_PICKAXE,
		CAT, // R
		ZOMBIE, // R
		DIMENSION_HOPPER,
		BONUS_STRUCTURE,
		CHEST,
		SNOW,
		DEMATERIALIZER,
		TIME_WARP,
		WORLD_BUILDER,
		FOREST,
		MOUNTAIN,
		VALLEY,
		WORK_TABLE,
		SNOWBALL,
		DOOM_BUNNY, // R
		DRAGON_CLAW,
		WOOD,
		LEAVES,
		HELICOPTER, // R
		BIRDIE, // R
		CRUSHER,
		SHINY_STONE_1, SHINY_STONE_2, SHINY_STONE_3,
		IRON_ORE,
		GOLD_ORE,
		PYRITE,
		SPHALERITE,
		OBSIDIAN,
		DRAGON_EGG,
		SMALL_WORLD, MED_WORLD, LARGE_WORLD,
		WAYPOINT,
		HELMET, CHESTPLATE, LEGGINGS, BOOTS,
		FORGE,
		IRON_BAR,
		GOLD_BAR,
		UPGRADE_STATION,
		DESERT,
		SAND,
		GLASS,
		MAGIC_BALL, REINFORCED_MAGIC_BALL, SHINY_MAGIC_BALL, GIANT_MAGIC_BALL,
		GEODE,
		AMETHYST, SAPPHIRE, JADE, PEARL, OPAL,
		MAGIC_WAND,
		PEDESTAL,

		numItems
	};

	int getItemOrder(Id id);
}

#endif
