#ifndef ID_ITEMS_H
#define ID_ITEMS_H

namespace item {
	// Order never changes!
	enum Id : uint16_t {
		DIRT = 0,
		STONE,
		BASIC_SWORD,
		BASIC_PICKAXE,
		CAT,
		ZOMBIE,
		DIMENSION_HOPPER,
		BONUS_STRUCTURE,
		CHEST,
		SNOW,
		DEMATERIALIZER,
		TIME_WARP,
		WORLD_BUILDER,
		FOREST,
		MOUNTAIN,
		VALLEY,
		WORK_TABLE,
		SNOW_BALL,
		DOOM_BUNNY,
		DRAGON_CLAW,
		WOOD,
		LEAVES,
		HELICOPTER,
		BIRDIE,
		CRUSHER,
		SHINY_STONE_1, SHINY_STONE_2, SHINY_STONE_3,
		IRON_ORE,
		GOLD_ORE,
		PYRITE,
		SPHALERITE,
		OBSIDIAN,
		DRAGON_EGG,
		SMALL_WORLD, MED_WORLD, LARGE_WORLD,
		WAYPOINT,
		HELMET, CHESTPLATE, LEGGINGS, BOOTS,
		FORGE,
		IRON_BAR,
		GOLD_BAR,
		UPGRADE_STATION,
		DESERT,
		SAND,
		GLASS,
		MAGIC_BALL, REINFORCED_MAGIC_BALL, SHINY_MAGIC_BALL, GIANT_MAGIC_BALL,
		GEODE,
		AMETHYST, SAPPHIRE, JADE, PEARL, OPAL,
		MAGIC_WAND,
		PEDESTAL,

		numItems
	};

	// TODO: operator bool(const Id& id) { return id != Id::numItems; }
	//bool toBool(const Id& id) { return id != Id::numItems; }
}

#endif
