#ifndef ID_ITEMS_H
#define ID_ITEMS_H

enum ItemId : uint16_t {
	// Normal Items
	AIR = 0, DIRT, STONE, SNOW, WOOD, LEAVES, SAND, GLASS,
	BOULDER1, BOULDER2, BOULDER3, SHINY_STONE_1, SHINY_STONE_2, SHINY_STONE_3,
	GEODE,
	DRAGON_EGG,

	// Usables
	DIMENSION_HOPPER, CHEST, WORLD_BUILDER, CRUSHER,
	UPGRADE_STATION, PORTAL, PEDESTAL,

	// Crafters
	WORK_TABLE, FORGE,

	// Spawners
	CAT, ZOMBIE, DOOM_BUNNY, HELICOPTER, BIRDIE,

	numItems
};

#endif